server:
  port: 8080
spring:
  application:
    name: SpringBootTeamSystem
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SpringBootTeamSystem?useSSL=false&serverTimezone=UTC
    username: root
    password: 661015......
  redis:
    host: 150.158.145.233
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
logging:
  level:
    com.wtmc.springbootteamsystem: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wtmc.springbootteamsystem.entity
